#!/usr/bin/env python3
"""Zip the report's reproducible material into a single archive with a
checksummed manifest: the raw commit/session dataset (data/dataset/output/),
the report-support data the table scripts read (data/*.csv, data/*.md), and
the scripts themselves (scripts/). Every entry is zipped at the same
relative path it has under report_on_code_development/, so extracting the
archive over an empty directory reproduces a working report_on_code_development/
layout -- the scripts run unmodified against the data sitting next to them.

Run after (re-)running ../data/dataset/build_dataset.py. Idempotent —
overwrites both the .zip and manifest.json.
"""
import csv
import hashlib
import importlib.util
import io
import json
import pprint
import zipfile
from pathlib import Path

HERE = Path(__file__).parent
REPORT_ROOT = HERE.parent  # report_on_code_development/
ARCHIVE_NAME = "apple_protobuf_extractor_dataset.zip"
PDC_DIR = REPORT_ROOT / "scripts" / "precommit_defect_census"

# scripts/precommit_defect_census/verdicts_data.py is never copied verbatim
# (see main()) -- it carries hand-written rationale/evidence for excluded
# sessions' episodes (audit-trail material, not for third parties). This
# generates an in_scope-only variant from the real module instead, written
# directly into the zip.
VERDICTS_DATA_SRC = PDC_DIR / "verdicts_data.py"
VERDICTS_DATA_ARCNAME = "scripts/precommit_defect_census/verdicts_data.py"


def _load_verdicts_data():
    spec = importlib.util.spec_from_file_location("verdicts_data", VERDICTS_DATA_SRC)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def public_verdicts_data_source(mod):
    in_scope_sids = {sid for sid, m in mod.SESSION_META.items() if m[1] == "in_scope"}
    session_meta = {sid: m for sid, m in mod.SESSION_META.items() if sid in in_scope_sids}
    verdicts = {k: v for k, v in mod.VERDICTS.items() if k[0] in in_scope_sids}
    extra_episodes = [e for e in mod.EXTRA_EPISODES if e[0] in in_scope_sids]

    return f'''"""Hand-verified session/episode classification data for
build_results_csv.py -- in_scope sessions only. Generated by
reproducibility_archive/build_archive.py from the real (internal)
verdicts_data.py, which also carries excluded sessions' rationale/evidence
(audit-trail material kept out of this archive) -- see that file's own
docstring.

dir_tag in SESSION_META is "june" (data/dataset/output/sessions/) or
"recov" (session_recovery_batch/, not archived -- every session below is
in_scope, so this is always "june").
"""

SESSION_META = {pprint.pformat(session_meta)}

VERDICTS = {pprint.pformat(verdicts)}

EXTRA_EPISODES = {pprint.pformat(extra_episodes)}
'''


# scripts/precommit_defect_census/{raw_scan_june_window.json,
# raw_scan_recovered_window.json, all_pytest_runs.csv} are pass-1 mechanical
# checkpoints (scan_selfcorrect.py / scan_all_pytest_runs.py), but they're
# keyed by individual pytest episode/run, not by session -- so they carry
# the same class of problem as verdicts_data.py above, just mechanical
# instead of hand-written: full pytest failure tracebacks, source snippets,
# and commands for every session, including the ones build_results_csv.py
# classifies non-in_scope. That includes all 22 episodes of
# excluded_test_quality_audit's session (4bae502f...) -- exactly the
# session the audit-trail concern was originally about, just at the raw-scan
# layer instead of the hand-verdict layer. None of these three files are
# copied verbatim (see main()); each is filtered to in_scope sessions only,
# using the real (internal) verdicts_data.py's SESSION_META as the scope
# lookup, and written directly into the zip. Filtering is behavior-
# preserving: build_results_csv.py only ever looks up a (session, ...) key
# from these files for sids it already got from its own SESSION_META import
# (the public, in_scope-only verdicts_data.py once archived), so a
# non-in_scope row here is never reachable by the shipped script anyway.
RAW_SCAN_JUNE_ARCNAME = "scripts/precommit_defect_census/raw_scan_june_window.json"
RAW_SCAN_RECOV_ARCNAME = "scripts/precommit_defect_census/raw_scan_recovered_window.json"
ALL_RUNS_ARCNAME = "scripts/precommit_defect_census/all_pytest_runs.csv"


def public_raw_scan_source(src_path, scope_by_sid):
    records = json.loads(src_path.read_text())
    in_scope = [r for r in records if scope_by_sid.get(r["session"]) == "in_scope"]
    return json.dumps(in_scope, indent=2)


def public_all_pytest_runs_source(scope_by_sid):
    with open(PDC_DIR / "all_pytest_runs.csv", newline="") as f:
        rows = list(csv.DictReader(f))
    in_scope_rows = [r for r in rows if scope_by_sid.get(r["session"]) == "in_scope"]
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=list(rows[0].keys()))
    w.writeheader()
    w.writerows(in_scope_rows)
    return buf.getvalue()

# Paths relative to REPORT_ROOT. Directories are walked recursively; files
# are included as-is. Every entry is zipped at this same relative path.
#
# NOTE: scripts/ as a whole is NOT included here (it once was, when it held
# only tables/; a bare "scripts" entry was found to sweep in ~68,000 files
# -- unrelated exploratory subprojects that have since grown alongside it
# under scripts/ (cfg_analysis/cfg/archive/, cfg_analysis/scratch/,
# archived_mechanism_decomposition/ -- which now also holds the retired
# discovery_mining/ pilot and the independent mechanism-decomposition
# redo --, archived_commit_message_accuracy/, response_reliability/ --
# its two figure scripts, already-computed data, and the decompose/
# categorize/score instruction documents (the codebooks/rubric a rerun
# would be scored against) are archived, via scripts/plots/,
# data/response_reliability_components_678.csv, data/full_response_
# dataset_678.csv (added 2026-09-21, the raw response text decompose/
# categorize actually run against), and the response_population_678/
# *_instructions.md entries below; the ~hundreds of per-response
# evidence-bundle/scored-verdict files those instructions were actually
# run against are not, same reasoning as build_dataset.py's raw session
# transcripts -- so decompose/categorize are genuinely re-runnable,
# scoring is not),
# several containing git worktrees under their own scratch/ dirs. List the
# specific report-regeneration scripts instead, matching scripts/README.md's
# scope.
SOURCES = [
    "data/dataset/output",
    "data/response_taxonomy_data.csv",
    "data/cfg_report.json",
    "data/summary_by_origin_category_by_rater.csv",
    # Minimal extract for tab:commit-type's Commits (Codex)/(Claude) columns:
    # just commit_hash + each rater's current category, no justification/
    # provenance content -- see scripts/commit_type_taxonomy/
    # commit_type_classification_by_rater_full.csv (also archived below, but as a
    # genuine runtime dependency of categorize_blocks.py's load_rater_maps()
    # now, not for its evidence-trail content) for the full justification
    # text this was thinned down from.
    "data/commit_type_classification_by_rater.csv",
    "data/instruction_taxonomy_components.csv",
    # Promoted snapshot of cfg_analysis/cfg/bug_fix_churn_per_block.csv
    # (from bug_fix_churn_analysis.py) for scripts/plots/plot_bug_hotspot_
    # map.py and plot_churn_composition_histogram.py to read -- re-copy if
    # the source CSV changes. Promoted 2026-09-21 alongside those two
    # scripts' move into scripts/plots/ (see that directory's README.md).
    "data/bug_fix_churn_per_block.csv",
    # Promoted snapshot of cfg_analysis/cfg/categorize_blocks.csv, enriched
    # 2026-09-21 with codex_category_normalized/claude_category_normalized
    # (computed by categorize_blocks.py's own resolve_category()/normalize_
    # origin_category() calls -- the same ones tally_by_rater() uses, so
    # there's no separate join logic to drift out of sync) and the
    # rater-independent in_139_population_or_override flag. Re-copy if
    # categorize_blocks.csv changes. Lets scripts/tables/build_commit_type_
    # cfg_block_table.py and scripts/plots/plot_block_reactive_share_by_
    # rater.py read it directly instead of importing categorize_blocks.py
    # -- see scripts/README.md's cfg_analysis/cfg/ section for the full
    # reasoning and the pre-existing arithmetic bug the switch caught.
    "data/cfg_block_categories_by_rater.csv",
    # New 2026-09-21: canonical, already-computed data behind
    # scripts/plots/plot_category_distribution.py, plot_error_count_per_
    # response_678.py, and scripts/tables/build_response_reliability_table.py
    # -- see the response_reliability/ note further below (with the
    # response_population_678/*_instructions.md entries) for what's
    # deliberately NOT included alongside it (the raw per-response evidence
    # bundles this was built from).
    "data/response_reliability_components_678.csv",
    # Added 2026-09-21: the raw response population (id, session, turn,
    # instruction_text, full_response_text -- one row per instruction, the
    # COMPLETE unfiltered assistant reply, no claim-level splitting) that
    # decompose_instructions.md/categorize_instructions.md below actually
    # need to be genuinely re-runnable, not just documentation of a process
    # that already happened. Built by scripts/corpus_context/build_full_
    # response_dataset.py (not itself archived -- like build_dataset.py, it
    # needs the raw session transcripts to run; this checkpoint doesn't).
    # Smoke-tested 2026-09-21: independently decomposed and categorized two
    # sample responses against this file, landed on the same categories
    # already recorded for those same components in data/response_
    # reliability_components_678.csv above.
    "data/full_response_dataset_678.csv",
    # Canonical copy of precommit_defect_census/results.csv for scripts/
    # tables/build_selfcorrect_table.py to read -- re-copy if results.csv
    # changes (see that directory's own NOTES.md).
    "data/precommit_defect_census_results.csv",
    "scripts/tables",
    # Every paper-figure script that reads genuinely canonical data/ and has
    # no sibling-module/sibling-data dependency on its original subproject
    # now lives here (moved 2026-09-21 from instruction_taxonomy/ and
    # response_reliability/, plus plot_bug_hotspot_map.py/plot_churn_
    # composition_histogram.py/plot_block_reactive_share_by_rater.py moved
    # from cfg_analysis/cfg/ the same day once data/bug_fix_churn_per_
    # block.csv and data/cfg_block_categories_by_rater.csv below made them
    # genuinely data/-sourced too -- see scripts/plots/README.md for the
    # full figure-to-script index and scripts/README.md's "## tables/ and
    # plots/" section for why the remaining CFG-block scripts stayed
    # embedded in cfg_analysis/cfg/ instead). Covers fig:components-per-
    # instruction, fig:codex-taxonomy-distribution, fig:category-
    # distribution, fig:error-count-per-response, fig:bug-hotspot-map,
    # fig:churn-composition-histogram, and fig:cfg-block-size-by-category
    # in one sweep.
    "scripts/plots",
    # response_reliability/'s own codebook/rubric documents -- what an
    # LLM rater is actually instructed to do at each pipeline stage that
    # built data/response_reliability_components_678.csv above (decompose
    # a response into atomic components, categorize each component, then
    # score it against the evidence for a verdict).
    # Decomposition + categorization are genuinely re-runnable as of
    # 2026-09-21, against fresh/different responses -- not just documented
    # -- now that data/full_response_dataset_678.csv above supplies the
    # raw response text these two stages need (previously missing: the
    # instructions were archived, but nothing to run them against was).
    # Scoring is NOT genuinely re-runnable from this archive, despite
    # score_instructions.md/codex_score_instructions.md being included --
    # it needs the per-response evidence bundles (grep/git-log results
    # pinned against specific commits, plus raw session-transcript
    # references), which are deliberately NOT included: ~hundreds of
    # files, too large (100MB+) and too much pipeline working-history for
    # this archive's scope, same reasoning as the raw session transcripts
    # build_dataset.py doesn't ship either. Both scoring instruction files
    # are still included (for documentation, and in case evidence is
    # supplied some other way) because the paper reports Codex and Claude
    # verdicts separately and the two raters are scored from different
    # instruction documents (codex_score_instructions.md's blind-cross-
    # check framing and broker-specific path notes vs.
    # score_instructions.md) even though the verdict rubric itself is the
    # same. Also deliberately NOT included: the scored-verdict JSON and
    # intermediate batching/settle files (response_population_678/
    # scored_verdicts_codex/, etc.) -- pipeline working-history, not
    # needed to either regenerate the existing figures/table or re-run
    # decomposition/categorization.
    "scripts/response_reliability/response_population_678/decompose_instructions.md",
    "scripts/response_reliability/response_population_678/categorize_instructions.md",
    "scripts/response_reliability/response_population_678/score_instructions.md",
    "scripts/response_reliability/response_population_678/codex_score_instructions.md",
    # Instruction behavioral-intent taxonomy (fig:codex-taxonomy-distribution,
    # fig:components-per-instruction). Unlike every other entry in this list,
    # this section is also meant to support RE-RUNNING the classification
    # itself, not just regenerating figures from data/instruction_taxonomy_
    # components.csv above -- so the codebook, its methodology log, and the
    # fuller-context input data (with prev_instruction/prev_response, not
    # just the final labels) are included too, deliberately going beyond
    # this archive's usual "checkpoint data + thin figure script" scope.
    # This won't produce an identical re-run (the pilot's amendment history
    # and blind-dispatch randomness aren't fully pinned), but it's enough to
    # redo the decompose-then-classify process against the same codebook
    # and data. The ~260 other historical/intermediate CSVs in
    # scripts/instruction_taxonomy/ (amendment retests, target+control
    # samples, pre-fix rounds) are deliberately NOT included -- they're the
    # pilot's own working history, not needed to regenerate or re-run.
    "scripts/instruction_taxonomy/instruction_codebook.md",
    "scripts/instruction_taxonomy/master_pool.csv",
    "scripts/instruction_taxonomy/classify_excluded_a.csv",
    "scripts/instruction_taxonomy/classify_excluded_b.csv",
    # 2026-09-15: the pre-Trigger x Method-scheme build pipeline
    # (build_csv.py, build_evidence*.py, extract_context.py, link_trackers.py,
    # NOTES.md, the old build_paper_table.py, and the data/ intermediates
    # they read/wrote, incl. classification_evidence.json) was moved to
    # scripts/commit_type_taxonomy/archive/ and is deliberately NOT archived
    # here: none of it was updated for the 2026-09-12 correction round
    # (TAXONOMY_DECISION_LOG.md SS20-23), so it no longer matches the current
    # CSV and would be misleading to ship alongside it.
    # commit_taxonomy_codebook.md is the instrument commits were scored
    # against. (data/commit_type_classification.csv -- the single-merged-
    # value predecessor of the by-rater files below -- was retired
    # 2026-09-23: categorize_blocks.py no longer reads it, having reduced
    # to a single hardwired root-checkpoint override; see that script's
    # module docstring.)
    # The table-regeneration script itself moved to scripts/tables/
    # build_commit_type_table.py 2026-09-21 (covered by the "scripts/tables"
    # whole-directory entry above).
    "scripts/commit_type_taxonomy/commit_taxonomy_codebook.md",
    # Also a runtime dependency of cfg_analysis/cfg/categorize_blocks.py's
    # load_rater_maps() (see below) -- codex_category/claude_category, the
    # per-rater answer data/commit_type_classification_by_rater.csv above
    # was thinned from.
    "scripts/commit_type_taxonomy/commit_type_classification_by_rater_full.csv",
    # CFG-block-level join (tab:cfg-block-category, fig:cfg-block-size-by-category):
    # same "list the specific files, not the whole exploratory subproject" scoping
    # as commit_type_taxonomy/ above -- cfg_analysis/cfg/archive/ and
    # cfg_analysis/scratch/ are NOT included (see the note at the top of
    # this list); the latter holds the pinned git worktrees.
    # data/cfg_report.json (listed above,
    # with the other data/*.csv sources) is the ALREADY-COMPUTED per-block
    # git-provenance data -- promoted there from cfg_analysis/cfg/, exactly
    # like data/dataset/output/ for the raw dataset. Unlike build_dataset.py
    # (whose raw session transcripts really are too large/private to ship),
    # cfg_builder.py/git_tracer.py's own raw input -- apple_protobuf_
    # extractor's git history -- has a small (2.7MB), standalone,
    # verified-faithful extraction at extractor_git_history/ below, built
    # 2026-09-15 via git-filter-repo against an isolated clone of the
    # monorepo (a prior version of this archive reused a bundle from
    # report_on_test_quality's own reproducibility package instead, but an
    # audit found its commit topology didn't reliably match the real
    # repository's directory structure at matching labeled commits, so it
    # was rebuilt from scratch). Verified: exact match against the real
    # repository on all 22 tracked files; a full fresh run reproduces every
    # one of data/cfg_report.json's 3,997 blocks exactly. See
    # reproducibility_archive/README.md's "Re-running the CFG-block
    # tracer" section for the exact recipe, build method, and verification
    # detail -- the one remaining caveat is commit-hash translation
    # (git-filter-repo necessarily rewrites hashes), not content fidelity.
    "scripts/cfg_analysis/cfg/cfg_builder.py",
    "scripts/cfg_analysis/cfg/git_tracer.py",
    "scripts/cfg_analysis/cfg/build_cfg_report.py",
    # categorize_blocks.py is the only place a CFG block ever gets a taxonomy
    # category attached -- build_commit_type_cfg_block_table.py and plot_
    # block_reactive_share_by_rater.py (tab:commit-type's Code blocks
    # columns, fig:cfg-block-size-by-category) moved to scripts/tables/
    # scripts/plots/ 2026-09-21 and are covered by those whole-directory
    # entries above; they now read data/cfg_block_categories_by_rater.csv
    # (also above) instead of importing this module directly.
    "scripts/cfg_analysis/cfg/categorize_blocks.py",
    # fig:cfg-block-origin-example: also needs the bundle above (reads source
    # lines directly from the cloned worktree, not from cfg_report.json) --
    # no longer flagged unreproducible in scripts/README.md's list.
    "scripts/cfg_analysis/cfg/plot_annotated_source_by_block.py",
    "reproducibility_archive/extractor_git_history/extractor_history.bundle",
    "reproducibility_archive/extractor_git_history/commit_hash_mapping.csv",
    "reproducibility_archive/extractor_git_history/build_bundle.sh",
    # "Reliability of generated code" section (fig:bug-hotspot-map,
    # fig:churn-composition-histogram): the two plot scripts are covered by
    # the "scripts/plots" whole-directory entry above now (moved there
    # 2026-09-21); this is just their upstream builder, which stayed in
    # cfg_analysis/cfg/ (imports categorize_blocks.py, carries its own
    # hand-verified per-commit override table). data/bug_fix_churn_per_
    # block.csv above is now archived directly (a cheap, already-computed
    # snapshot, same as data/cfg_report.json); fix_churn_histogram.csv is
    # still NOT archived -- it backs no current figure (see cfg_analysis/
    # cfg/README.md's archive/ section) and is fully re-derivable anyway by
    # running bug_fix_churn_analysis.py against cfg_report.json (listed
    # above) and Codex's current commit-type classification (categorize_
    # blocks.load_rater_maps(), reading commit_type_classification_by_
    # rater_full.csv, listed below).
    "scripts/cfg_analysis/cfg/bug_fix_churn_analysis.py",
    "academic_plot_style.py",  # imported by every matplotlib script under scripts/plots/ (including the three CFG-block figures after their 2026-09-21 move), for IEEEtran figure styling
    # fig:swechat-ai-commit-distributions's own script is NOT archived --
    # its source data (a HuggingFace-gated dataset requiring login + terms
    # acceptance) isn't archived either, so the script can't run here.
    # "Reliability of Claude code output" section (tab:selfcorrect): same
    # already-computed-data + regeneration-script split as the two entries
    # above. raw_scan_*.json and all_pytest_runs.csv are the ALREADY-COMPUTED
    # checkpoints (cheap to store, the equivalent of cfg_report.json) --
    # scan_selfcorrect.py / scan_all_pytest_runs.py, the tools that derive
    # them from raw Claude Code session .jsonl transcripts, are deliberately
    # NOT included (re-running pass 1 needs the FULL raw-transcript
    # directories these checkpoints were built from, not just the curated
    # subset below -- matching how cfg_builder.py/git_tracer.py stay
    # excluded even though build_cfg_report.py itself is included).
    # Like verdicts_data.py below, none of the three checkpoints
    # (raw_scan_june_window.json, raw_scan_recovered_window.json,
    # all_pytest_runs.csv) are copied verbatim -- see main() and the
    # public_raw_scan_source()/public_all_pytest_runs_source() comment
    # above: each carries full pytest episode content (tracebacks, source
    # snippets, commands) for non-in_scope sessions too, so each is
    # filtered to in_scope rows and generated fresh into the zip instead.
    # build_results_csv.py (pass 2 -- dedup + hand-verified classification,
    # reading the two pass-1 checkpoints) IS genuinely re-runnable, as of
    # 2026-09-22: it needs the raw session .jsonl for two things (re-reading
    # a specific line to dedup, and pulling a literal evidence quote), split
    # across two sources -- JUNE_DIR (data/dataset/output/sessions/,
    # already archived via the "data/dataset/output" entry above). Raw
    # transcripts for sessions build_results_csv.py classifies non-in_scope
    # (adjacent-subproject, a different research phase, or outside the
    # paper's population window) are deliberately NOT archived -- their
    # episodes are audit-trail material (hand-written rationale + a literal
    # evidence quote), not part of the published table, and don't belong in
    # front of third parties. main() skips a missing recovery file
    # gracefully for any non-in_scope session, so this doesn't break
    # anything: build_results_csv.py against this archive's contents alone
    # still reproduces every in_scope row of results.csv exactly, and
    # build_selfcorrect_table.py off that still reproduces tab:selfcorrect's
    # published figures exactly -- see "Re-running the pre-commit defect
    # census" below. results.csv itself is archived directly (like
    # commit_type_classification_by_rater.csv above) since it's small and is the
    # literal data the paper table cites -- it also still carries the
    # non-in_scope rows' verdicts (not the underlying transcripts), which
    # is fine since those are already-completed judgements, not raw
    # material. build_selfcorrect_table.py reads data/precommit_defect_
    # census_results.csv (listed above), a copy of results.csv below.
    "scripts/precommit_defect_census/build_results_csv.py",
    # Codebook for verdicts_data.py's hand classification (2026-09-23) --
    # same role as commit_type_taxonomy/commit_taxonomy_codebook.md above.
    "scripts/precommit_defect_census/selfcorrect_verdict_codebook.md",
]

# Individual files to drop out of a whole-directory SOURCES entry above --
# pure documentation, not read by any script, not needed to run anything.
EXCLUDE = {
    "scripts/plots/README.md",
}


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def collect_files():
    files = []
    for rel in SOURCES:
        p = REPORT_ROOT / rel
        if not p.exists():
            raise SystemExit(f"{p} not found (source: {rel})")
        if p.is_dir():
            files.extend(sorted(
                x for x in p.rglob("*")
                if x.is_file() and "__pycache__" not in x.parts and x.suffix != ".pyc"
                and str(x.relative_to(REPORT_ROOT)) not in EXCLUDE
            ))
        else:
            files.append(p)
    return files


def main():
    files = collect_files()
    archive_path = HERE / ARCHIVE_NAME

    print(f"Zipping {len(files) + 1} files from {REPORT_ROOT}...")
    entries = []
    with zipfile.ZipFile(archive_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for p in files:
            rel = p.relative_to(REPORT_ROOT)
            zf.write(p, arcname=str(rel))
            entries.append({
                "path": str(rel),
                "size_bytes": p.stat().st_size,
                "sha256": sha256_file(p),
            })

        verdicts_mod = _load_verdicts_data()
        scope_by_sid = {sid: m[1] for sid, m in verdicts_mod.SESSION_META.items()}

        generated = [
            (VERDICTS_DATA_ARCNAME, public_verdicts_data_source(verdicts_mod)),
            (RAW_SCAN_JUNE_ARCNAME, public_raw_scan_source(PDC_DIR / "raw_scan_june_window.json", scope_by_sid)),
            (RAW_SCAN_RECOV_ARCNAME, public_raw_scan_source(PDC_DIR / "raw_scan_recovered_window.json", scope_by_sid)),
            (ALL_RUNS_ARCNAME, public_all_pytest_runs_source(scope_by_sid)),
        ]
        for arcname, src in generated:
            zf.writestr(arcname, src)
            entries.append({
                "path": arcname,
                "size_bytes": len(src.encode()),
                "sha256": hashlib.sha256(src.encode()).hexdigest(),
            })

    archive_sha256 = sha256_file(archive_path)
    manifest = {
        "archive_filename": ARCHIVE_NAME,
        "archive_sha256": archive_sha256,
        "archive_size_bytes": archive_path.stat().st_size,
        "source_paths": SOURCES,
        "extract_layout": "each entry's zip path is its real path relative to report_on_code_development/ -- extract there to get a working layout",
        "generated_by": "report_on_code_development/data/dataset/build_dataset.py + report_on_code_development/reproducibility_archive/build_archive.py",
        "file_count": len(entries),
        "total_uncompressed_bytes": sum(e["size_bytes"] for e in entries),
        "files": entries,
    }
    (HERE / "manifest.json").write_text(json.dumps(manifest, indent=2))

    print(f"  archive: {archive_path} ({archive_path.stat().st_size / 1e6:.1f} MB, sha256 {archive_sha256[:12]}...)")
    print(f"  manifest: {HERE / 'manifest.json'} ({len(entries)} files)")


if __name__ == "__main__":
    main()
